Executable  = condor_script.sh
Universe    = vanilla
Input       = /dev/null
Arguments   = $(filename1) $(filename2)
Output      = /sphenix/user/jpark4/sPHENIX_software/sPHENIX_PmonTpcBcoCheck/log/$(Cluster).$(Process).out
Error       = /sphenix/user/jpark4/sPHENIX_software/sPHENIX_PmonTpcBcoCheck/log/$(Cluster).$(Process).err
Log         = /sphenix/user/jpark4/sPHENIX_software/sPHENIX_PmonTpcBcoCheck/log/$(Cluster).$(Process).log
Initialdir  = /sphenix/user/jpark4/sPHENIX_software/sPHENIX_PmonTpcBcoCheck
PeriodicHold  = (NumJobStarts>=1 && JobStatus == 1)
request_memory = 8192MB
Queue filename1 filename2 from queue.list
