Universe           = vanilla
Notification       = Never
PeriodicHold       = (NumJobStarts>=1 && JobStatus == 1)
Initialdir         = XXXX
Executable         = $(Initialdir)/macro/runHFreco.sh
request_memory     = 4GB
Priority           = 20
job_lease_duration = 3600
OutDir             = $(Initialdir)/root/
Output             = $(Initialdir)/log/job-Data-$(Cluster)-$(Process).out
Error              = $(Initialdir)/log/job-Data-$(Cluster)-$(Process).err
Log                = $(Initialdir)/log/job-Data-$(Cluster)-$(Process).log
Arguments          = $(events) $(file) $(path) $(OutDir) $(skip)
Queue events file path skip from fileLists/file_run53877_0.list
